### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by mosquito** [JaneTurueva/py-leet#6]
Could you provide performance tests for:
* thousands strings by 512 bytes
* thousands strings by 64 kilobytes
* hundreds strings by 1 megabytes
* tens strings by 1 megabytes
* couple of strings by 10 megabytes

**Comment by JaneTurueva** [comment]
@mosquito, thank you for suggestion, will add shortly.

**Comment by JaneTurueva** [comment]
@mosquito please, see README.rst
